### ISSUE TITLE
Error while installing through composer

### ISSUE THREAD

**Issue by christogonus** [bajoski34/Laravel#1]
Hi there,

I get error trying to pull this in through composer.
Here's a screenshot of the error https://prnt.sc/zF1vm2oIv8Cd

The app is on Laravel 10

**Comment by bajoski34** [comment]
Hi @christogonus

Updates have been made to resolve this please kindly install the package via composer using `composer require abraham-flutterwave/laravel-payment`

This new version (1.0.2) supports Laravel 10.

Regards.
